### ISSUE TITLE
Limited companies not registered in the UK

### ISSUE THREAD

**Issue by johnhemming** [hmrc/vat-returns#35]
Happy new year

I have a number of people who are trying to sign up to MTD for vat that are limited companies not registered in the UK (as companies, but registered in the UK for VAT).

Can they join MTD for VAT (they are incidentally mandated to so do) and if so how do they do it.

**Comment by lewishay** [comment]
Hi johnhemming,

Apologies but this is not the correct avenue for these sorts of questions. This is a repository for one of many microservices that a development team contribute to and monitor.

If users still need help then they can contact the HMRC helpline on:

- 0300 200 3700 if they are inside the UK
- +44 2920 501 261 if they are outside the UK

Alternatively, users can click the "Get help with this page" link towards the bottom of the page on certain GOV UK pages and this will allow them to describe their issue and raise a ticket to be investigated.

Thank you.
